CREATE DATABASE ejercicio14;
USE ejercicio14;
CREATE TABLE grupos(
IdGrupo INT AUTO_INCREMENT PRIMARY KEY, 
Nombre VARCHAR(20));

CREATE TABLE contactos(
ContactoID INT AUTO_INCREMENT PRIMARY KEY,
ComentarioDescripcion VARCHAR(100),
IdGrupo INT,
FOREIGN KEY (IdGrupo) REFERENCES grupos(IdGrupo)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE usuarios(
UsuariosID INT AUTO_INCREMENT PRIMARY KEY,
Contraseña VARCHAR(20),
Nombre VARCHAR(20),
Apellidos VARCHAR(20),
Foto VARCHAR(50),
ContactoID INT ,
FOREIGN KEY (ContactoID) REFERENCES contactos(ContactoID)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE comentarios(
ComentarioID INT AUTO_INCREMENT PRIMARY KEY,
Texto VARCHAR(100),
Imagen VARCHAR(50),
Visibilidad VARCHAR(50),
ContactoID INT,
FOREIGN KEY (ContactoID) REFERENCES contactos(ContactoID)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE usuariosNoFamosos(
Email VARCHAR(20),
Direccion VARCHAR(50),
Telefono INT,
UsuariosID INT,
FOREIGN KEY (UsuariosID) REFERENCES usuarios(UsuariosID)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE usuariosBloqueados(
Nombre VARCHAR(20),
UsuariosID INT PRIMARY KEY,
FOREIGN KEY (UsuariosID) REFERENCES usuarios(UsuariosID)
ON DELETE CASCADE ON UPDATE CASCADE);