DROP DATABASE IF EXISTS Directores;

CREATE DATABASE Directores;
USE Directores;

CREATE TABLE Despachos(
Numero INT,
Capacidad INT,
PRIMARY KEY (Numero)
);

CREATE TABLE Directores(
DNI VARCHAR(8),
NomApels NVARCHAR(255),
DNIJefe VARCHAR(8),
Despacho INT,
PRIMARY KEY (DNI),
FOREIGN KEY (Despacho) REFERENCES Despachos (Numero) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (DNIJefe) REFERENCES Directores (DNI) ON DELETE CASCADE ON UPDATE CASCADE
);
